# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app_doan_xe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app_doan_xe
  pod 'SQLite.swift'
  pod 'SwiftKeychainWrapper'
  pod 'CollectionViewCenteredFlowLayout'
  pod 'NewPopMenu'
end
